<?php
/**
 * @author quantm
 * @date: 28/03/2016 12:39
 */

namespace QtmTest;
use Qtm\QueryBuilder\Queryable;

/**
 * @property Queryable $db
 */
class AppTestCase extends \PHPUnit_Framework_TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $config = [
            'host' => 'localhost',
            'database' => 'queryable',
            'username' => 'root',
            'password' => 'quantm'
        ];

        $this->db = new Queryable($config);
    }
}